const FALLBACK_SUPABASE_URL =
  "https://ftebinspsqpzupimsndp.supabase.co" as const;
const FALLBACK_SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0ZWJpbnNwc3FwenVwaW1zbmRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzOTQ1ODcsImV4cCI6MjA3ODk3MDU4N30.-ZI6Kkm46xiNCJpos_Byj0IX0JooDSy7itw2vMINVpA" as const;

if (!process.env.NEXT_PUBLIC_SUPABASE_URL) {
  process.env.NEXT_PUBLIC_SUPABASE_URL = FALLBACK_SUPABASE_URL;
}

if (!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY = FALLBACK_SUPABASE_ANON_KEY;
}

export const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ?? FALLBACK_SUPABASE_URL;
export const SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? FALLBACK_SUPABASE_ANON_KEY;
